In [13]:
import pandas as pd

In [14]:
df=pd.read_csv('Student_Marks.csv')

In [15]:
df.head(3)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [16]:
df.columns=['sinif', 'saat','puan']
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [17]:
from sklearn.linear_model import LinearRegression


y=df['puan']
X=df[['sinif','saat']]
lm=LinearRegression()

In [18]:
model=lm.fit(X,y)

In [19]:
model.coef_  #katsayılar


array([1.86405074, 5.39917879])

In [20]:
model.intercept_ #sabit

np.float64(-7.456346231178355)

In [23]:
model.predict([[4,10]]) #tahmin

C:\Users\LENOVO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53.99164461])

In [25]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [37]:
features1=pd.DataFrame([[4,3.133]] , columns=['sinif','saat'])
s1=model.predict(features1)

In [38]:
s1

array([16.91548388])